### ISSUE TITLE
HashCode issue on IPv6Address

### ISSUE THREAD

**Issue by secr3t** [seancfoley/IPAddress#104]
# Version : 5.4.0

## IPv6Address's hashCode method is something strange.
IPv4Address, it calculates different hashCode value when subnet is different.
But when it comes to IPv6Address, it calculates same hashCode value when subnet is different.

I found this while test with set.

And here is some test codes.

```java
        @Test
        public void test_ip_addr() {
            final List<String> list = List.of("192.4.4.0/24", "192.4.4.0/25", "192.4.4.0/26", "192.4.4.0",
                                              "2401:e180:8d61:6599:6805:6953:b1f9:9df8",
                                              "2401:e180:8d61:6599:6805:6953:b1f9:9df9",
                                              "2401:e180:8d61:6599:6805:6953:b1f9:9dfb",
                                              "2401:e180:8d61:6599:6805:6953:b1f9:9dfb/128",
                                              "2401:e180:8d61:6599:6805:6953:b1f9:9dfb/126");
            list.forEach(s -> {
                IPAddressString ipStr = new IPAddressString(s);
                IPAddress ipAddress = ipStr.getAddress();
                System.out.printf("IP Addr %s - hashCode %d\n", ipAddress, ipAddress.hashCode());
            });
        }
```

```text
IP Addr 192.4.4.0/24 - hashCode 206068446
IP Addr 192.4.4.0/25 - hashCode 206068318
IP Addr 192.4.4.0/26 - hashCode 206068254
IP Addr 192.4.4.0 - hashCode 6647361
IP Addr 2401:e180:8d61:6599:6805:6953:b1f9:9df8 - hashCode 2098772805
IP Addr 2401:e180:8d61:6599:6805:6953:b1f9:9df9 - hashCode 2098772806
IP Addr 2401:e180:8d61:6599:6805:6953:b1f9:9dfb - hashCode 2098772808
IP Addr 2401:e180:8d61:6599:6805:6953:b1f9:9dfb/128 - hashCode 2098772808
IP Addr 2401:e180:8d61:6599:6805:6953:b1f9:9dfb/126 - hashCode 2098772808
```

**Comment by seancfoley** [comment]
The premise of this issue is incorrect, in multiple ways.

1. A prefix length, on its own, does not affect the hashcode, see [here](https://seancfoley.github.io/IPAddress/ipaddress.html#prefix-length-and-equality).  That is because an address with the same value or value range should be equal to any other address with the same value or value range.  Whether a prefix has been identified does not matter, it is the same address.

-----------

2. However, a prefix length for a zero-host address means the address is a subnet, see [here](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address)  or [here](https://seancfoley.github.io/IPAddress/ipaddress.html#parsing-addresses-with-prefix-length
).

In your example, 2401:e180:8d61:6599:6805:6953:b1f9:9dfb/126 has a non-zero host so it is the same as 2401:e180:8d61:6599:6805:6953:b1f9:9dfb.  2401:e180:8d61:6599:6805:6953:b1f9:9dfb/128 has a prefix length indicating no host at all, so it is the same as 2401:e180:8d61:6599:6805:6953:b1f9:9dfb.  All three addresses are equal, since they all indicate the same address value.  So they must have the same hashcode, according to the [hashcode contract](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()).

However, for your IPv4 examples, all the addresses with prefixes have a host of zero, so they are all subnets.
192.4.4.0/24 is the same as 192.4.4.0-255
192.4.4.0/25 is the same as 192.4.4.0-127
192.4.4.0/26 is the same as 192.4.4.0-63
So they are all different, and none are the same as 192.4.4.0
So they can all have different hashcodes, and they do.

--------------

3. Finally, note that Java hashcode values are 32 bits, because an int is 32 bits.  IPv6 addresses are 64 bits.  So it is literally impossible to calculate a unique hashcode for every IPv6 address, no matter what method is chosen.  In fact, on average every single IPv6 address will have 2 to the power of 32 other unequal addresses with the same hashcode.  Also add to the fact that this library supports subnets with value ranges, indicating even more hashcode collisions, amongst both IPv4 and IPv6.

However, the [hashcode contract](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()) is adhered to, regardless.   You cannot have two equals objects with different hashcodes, but you can have two unequal objects with the same hashcode.  Hash tables such as java.util.HashMap and java.util.Hashtable will continue to work properly when two unequal objects have the same hashcode.

**Comment by secr3t** [comment]
Thank you for detailed reply. I was mistaken about ipv6.
