### ISSUE TITLE
Issue with isZero and isMax

### ISSUE THREAD

**Issue by tlf30** [seancfoley/IPAddress#110]
Hello,
I hope I am doing this correctly.
I am trying to iterate over a block of IPs based on the subnet of a given IP, and want to ignore the zero and max address in the subnet.

My code is like this:
```java
IPAddress addr = new IPAddressString(fullAddrStr).getAddress();
IPAddress block = addr.toPrefixBlock();
ipRange = block.toSequentialRange();
```
```java
ConnectionManager dcm = new ConnectionManager(lcm);
var iterator = ipRange.stream().iterator();
var count = ipRange.getCount().intValue();
int index = 0;
while (iterator.hasNext()) {
    var addr = iterator.next();
    System.out.println("Checking (1) " + addr.toString() + " Zero=" + addr.isZero() + " Broadcast=" + addr.isMax());
    if (addr.isZero() || addr.isMax()) {
        continue;
    }
    dcm.setPath(port.getPath() + "," + addr.toString());
    job.setStatus("Probing: " + addr.toString());
    job.setProgress((int) ((index / (float) count) * 100f));
    probeDevice(devices, port, dcm);
    index++;
}
```

An example `fullAddrStr` is `192.168.1.12/255.255.255.0`.

The `addr.isZero()` and `addr.isMax()` are never true though, causing my logic to attempt to probe the `.0` and `.255` addresses in this example. 

Thank you,
Trevor

**Comment by seancfoley** [comment]
What you want is 'isZeroHost'. Seems I don't have an isMaxHost, which was an oversight. But you can use 'includesZeroHost' and 'includesMaxHost' as well, they do the same thing for single addresses.

Also, you can simplify to:
```java
IPAddress addr = new IPAddressString(fullAddrStr).getAddress();
IPAddress iterator = addr.toPrefixBlock().iterator();
```
And then use that iterator.

Instead of checking includesZeroHost just skip the first, since the zero host is always first. And of course the max host is always the last.

**Comment by tlf30** [comment]
Thanks for the quick reply. 
I tested `isZeroHost` and `includesZero` and both are also never true. 
I will need to re-work the logic to skip the first and last address as in my program it gets ranges from things other than subnets too. But I think as a quick workaround I will implement that.

**Comment by seancfoley** [comment]
The real problem is that the way you constructed the iterator, you ended up dropping the prefix length.  A sequential range has no associated prefix length, so when you converted to the sequential range the prefix length was dropped.  If there is no prefix length, then there is no host, and so `includesMaxHost` and `includesZeroHost` will always be false.  Using `includesMax` simply checks for "255.255.255.255", the max address.  Using `includesZero` or `isZero` checks for "0.0.0.0".  Neither is what you wanted.

There are plenty of options.  One is to use your original code and supply the prefix length to `includesZeroHost` and `includesMaxHost`:
```
static void method1(String fullAddrStr) {
	IPAddress addr = new IPAddressString(fullAddrStr).getAddress();
	IPAddress block = addr.toPrefixBlock();
	var prefixLen = block.getPrefixLength();
	var ipRange = block.toSequentialRange();
	var iterator = ipRange.stream().iterator();
	var count = ipRange.getCount().intValue();
	int index = 0;
	while (iterator.hasNext()) {
		var iterAddr = iterator.next();
		System.out.println("Checking " + iterAddr.toString() + " Zero=" + iterAddr.includesZeroHost(prefixLen) + " Broadcast=" + iterAddr.includesMaxHost(prefixLen));
		if (iterAddr.includesZeroHost(prefixLen) || iterAddr.includesMaxHost(prefixLen)) {
			continue;
		}
		String status = "Probing: " + iterAddr.toString();
		int progress = ((int) ((index / (float) count) * 100f));
		System.out.println(status + " " + progress);
		index++;
	}
}
```
However, you do not need the sequential range, nor the stream.  Another option is to not drop the prefix length until after you obtain each address:
```
static void method2(String fullAddrStr) {
	IPAddress addr = new IPAddressString(fullAddrStr).getAddress();
	IPAddress block = addr.toPrefixBlock();
	var iterator = block.iterator();
	var count = block.getCount().intValue();
	int index = 0;
	while (iterator.hasNext()) {
		var iterAddr = iterator.next();
		System.out.println("Checking " + iterAddr.toString() + " Zero=" + iterAddr.includesZeroHost() + " Broadcast=" + iterAddr.includesMaxHost());
		if (iterAddr.includesZeroHost() || iterAddr.includesMaxHost()) {
			continue;
		}
		iterAddr = iterAddr.withoutPrefixLength();
		String status = "Probing: " + iterAddr.toString();
		int progress = ((int) ((index / (float) count) * 100f));
		System.out.println(status + " " + progress);
		index++;
	}
}
```
The third suggestion, which is most efficient, is to avoid checking the host at all.  You don't need to, because the first address is always the zero host and the last is always the broadcast address:
```
static void method3(String fullAddrStr) {
	IPAddress addr = new IPAddressString(fullAddrStr).getAddress();
	IPAddress block = addr.toPrefixBlock();
	var iterator = block.withoutPrefixLength().iterator();
	var count = block.getCount().intValue();
	int index = 0;
	if (iterator.hasNext()) {
		iterator.next(); // skip zero host
		var iterAddr = iterator.next();
		while (iterator.hasNext()) { // is not broadcast
			String status = "Probing: " + iterAddr.toString();
			int progress = ((int) ((index / (float) count) * 100f));
			System.out.println(status + " " + progress);
			index++;
			iterAddr = iterator.next();
		}
	}
}
```

**Comment by tlf30** [comment]
The method1 example works great, thank you
