### ISSUE TITLE
IPAddressString Support Format startIP-endIP for IP range

### ISSUE THREAD

**Issue by SaeedZhiany** [seancfoley/IPAddress#124]
Hi @seancfoley,

I know my problem can be fixed using other utilities but I Prefer to use IPAddressString.

in my application, I have `startIP` and `endIP` of an IP range. they are dynamic and users can change them.
I want to create an IPAddressString first and then get an IPAddressSeqRange from it like this:

```java
IPAddressString rangeString = new IPAddressString(startIp + "-" + endIP);
IPAddressSeqRange sequentialRange = rangeString.getSequentialRange();
// the other logics
```

but I get `null` for the `sequentialRange` for the inputs `startIp=10.140.20.50` and `endIP=10.140.150.20` (or any other values).

Please note that I know I can parse my inputs and create a new string like this: `10.140.20-150.50-20`
but as you can see, it needs extra string manipulation, also the fourth octet in the startIP is greater than the fourth octet in the endIP. I'm looking for a simple notation similar to the above (`startIp + "-" + endIP`). I looked at the documentation but found no similar example to my case.

is it achievable by this library?

**Comment by seancfoley** [comment]
Yes this is achievable.  The problem with those two lines of code is that you are parsing the string 10.140.20.50-10.140.150.20.  The "-" character indicates a range within a segment, so that is parse as an address with the segments 10, 140, 20, 50 to 10, 140, 150, and 20.  

The class IPAddressString does not parse range strings, it parses address strings.  So, the string must be something corresponding to a subnet, and then getSequentialRange of IPAddressString can give you the range of that subnet.

However, a sequential range can be constructed more directly, it does not have to be encoded as a single string.

Since you are starting with two full-formed addresses, what you do instead is:
```
String startIp = "10.140.20.50", endIP = "10.140.150.20";
IPAddressSeqRange sequentialRange = 
	new IPAddressString(startIp).getAddress().spanWithRange(
		new IPAddressString(endIP).getAddress());
System.out.println(sequentialRange); // 10.140.20.50 -> 10.140.150.20
```
