### ISSUE TITLE
github.seancfoley:ipaddress:5.5.1 build is failing 

### ISSUE THREAD

**Issue by deepeshpatel3434** [seancfoley/IPAddress#131]
Hello, 

I'm experiencing an issue with building the following library. Could someone please help me troubleshoot this?

Attached are the logs for your reference.

[build-ipaddress-5.5.1-2024-11-11-06-24-24-033-72485947.txt](https://github.com/user-attachments/files/17702949/build-ipaddress-5.5.1-2024-11-11-06-24-24-033-72485947.txt)

**Comment by seancfoley** [comment]
That's your python script failing, not mine.  I cannot debug your code.  

Your code is telling you that a directory does not exist on your build machine.  

But you don't even need to build this library, since I provide pre-built jars to use.  I don't know why you would do that.

This is not an issue with this library, so I am closing this.  This is an issue with your own code.
