### ISSUE TITLE
 Build Failure with IPAddress 5.5.1 - Assistance Required

### ISSUE THREAD

**Issue by deepeshpatel3434** [seancfoley/IPAddress#132]
Hi Team,

I am currently working with IPAddress version 5.5.1, which I cloned from the following repository:
https://github.com/seancfoley/IPAddress/archive/refs/tags/v5.5.1.zip

While trying to build the project, I encountered the following error:
$ ant -f /build.xml compile -Djavadoc.skip=true
Buildfile: C:\Program Files\Git\build.xml does not exist!
Build failed

Below are the steps and details for further context:

Within IPAddress-5.5.1, I navigated to the IPAddress/ directory, where the build.xml file exists.
Apache Ant: Apache Ant(TM) version 1.10.15 

Error Details:
Command used: $ ant -f /build.xml compile -Djavadoc.skip=true

Result: Buildfile: C:\Program Files\Git\build.xml does not exist!

The build.xml file is located in /d/BAprocess/ipaddress/IPAddress-5.5.1/IPAddress-5.5.1/IPAddress/, but it appears that the Ant command is unable to locate it.

Could you please advise on how to resolve this issue?

<img width="943" alt="image" src="https://github.com/user-attachments/assets/60ab985d-c553-45b6-b5d0-ebd15d52922d">

**Comment by seancfoley** [comment]
I already explained to you that I will not debug your own build of this repository.

I provide pre-built jars to use. I don't know why you would be trying to build it yourself.  I do not support that, since there is no reason to do that.

Issues are for bugs or other problems with the code in this repository.  Issues are not to be used as a means to provide you a tutorial on how to use ant or other build tools.
