### ISSUE TITLE
Using IPAddressGenerator() with ColdFusion/CFML

### ISSUE THREAD

**Issue by JamoCA** [seancfoley/IPAddress#133]
I downloaded 5.5.1 and would like to use the IPAddress library `IPAddressGenerator()` method with Adobe ColdFusion/CFML (which runs on Java).

I can access the `IPAddressString` method without any issues.
```cfml
<cfset ipAddressString = createobject("java", "inet.ipaddr.IPAddressString")>
<cfset ip = ipAddressString.init("2001:0db8:85a3:08d3:1319:0000:0370:7348")>

<cfoutput>
<pre>
isValid() = #ip.isValid()#
isIPAddress() = #ip.isIPAddress()#
isLoopback() = #ip.isLoopback()#
isIPv4() = #ip.isIPv4()#
isIPv6() = #ip.isIPv6()#
isMixedIPv6() = #ip.isMixedIPv6()#
toNormalizedString() = #ip.toNormalizedString()#
</pre>
</cfoutput>
```

I can also use the following logic to convert IPv4 & IPv6 IP addresses to binary.
```cfml
public any function iptoBinary(string ipString) hint="Converts IPV4 & IPV6 string representations to 4 or 16 bytes binary value." {
	return createobject("java", "inet.ipaddr.IPAddressString").init(javacast("string", trim(arguments.ipString))).getAddress().getBytes();
}
```

But I can't figure out how to access the `IPAddressGenerator` method to convert binary to string. I'm not sure how to access the generator.  This, and other methods, haven't work.
```cfml
IPAddressGenerator = createobject("java", "inet.ipaddr.IPAddressNetwork.IPAddressGenerator");
```

Thanks.

**Comment by seancfoley** [comment]
I am not familiar with CFML, but I suspect this is because of the way inner classes are represented in Java bytecode.  In Java bytecode, there really is no such thing as an inner class (not entirely true, there are indicators of inner class relationships in order to correctly manager permissions).  An inner class is actually compiled to a class with a different name, following certain rules.  The rules differ for named vs anonymous classes.  For named classes, the outer and inner name are joined by a '$'.  So in this case, the bytecode class name is "inet.ipaddr.IPAddressNetwork$IPAddressGenerator".  

You do not need to know the naming rules, you can find the class name for an inner class by looking inside the jar file for the class file.  A jar file is just a zip file.  In there you will see a file named inet/ipaddr/IPAddressNetwork$IPAddressGenerator.class, and so converting each '/' in the path to '.' gives the class name..

My suspicion seems to be confirmed after a web search found this: https://www.bennadel.com/blog/1370-ask-ben-instantiating-nested-java-classes-in-coldfusion.htm

So I'd recommend you try out "inet.ipaddr.IPAddressNetwork$IPAddressGenerator".

**Comment by JamoCA** [comment]
You are correct and thank you for the explanation.  I previously navigated the JAR as a ZIP file, viewed the JavaDoc, searched the repository codebase and knew that `IPAddressGenerator` was part of `IPAddressNetwork`, but couldn't recall the syntax.  I also thought that Ben had blogged about it and had explicitly searched Google for his website (since he doesn't have a search feature) and came up empty. (Ben has also blogged on the topic of `createObject` a lot.)

This is what basically works for ColdFusion (without any error catching):

```cfml
ipAddressGenerator = createobject("java", "inet.ipaddr.IPAddressNetwork$IPAddressGenerator");
ipString = ipAddressGenerator.from("2001:0db8:85a3:08d3:1319:0000:0370:7348").toString();
```

Thanks!
