### ISSUE TITLE
Hostname ipAddress bug?

### ISSUE THREAD

**Issue by alperenp** [seancfoley/IPAddress#19]
Greetings,

First of all thanks for providing awesome work. I hope still you continue on the project.

I have encountered a weird thing while using the library you provided. See the following:
```
HostName hostName = new HostName("23.23.43");
String host = hostName.getHost(); // host = 23.23.0.43
```

I'm not sure whether this is expected behavior or a problem. I would expect to have either null string or some sort of exception claiming illegal argument.

I debug a bit and see that host value in HostName objectis "23.23.43" it is converted into valid IP during getHost() method.

If you can clarify (or solve) it would be appreciated!

Best regards,
Alperen

**Comment by seancfoley** [comment]
Hello, thanks for the compliment, feel free to provide suggestions for additional and useful functionality and don't forget to star the project since you like it.

Regarding the question, this is expected behaviour.  If you type an address like that into most browsers (ie http://23.23.43) you will see the same result, the address will be interpreted as 23.23.0.43.

That string is an IPv4 string format that was originally introduced by the inet_aton utility in BSD Unix and has persisted until this day in the various Unix and Linux flavours, and has also spread elsewhere into browsers and other software.

https://linux.die.net/man/3/inet_aton

See another example and some more sample code on stack overflow: https://stackoverflow.com/a/40120669/6801443

This library provides the flexibility to choose if you wish to treat that address as invalid.  You can either do it on a case-by-case basis or make it the default behaviour.

For example:

	HostNameParameters hostParams = new HostNameParameters.Builder().
		getAddressOptionsBuilder().allow_inet_aton(false).getParentBuilder().toParams();
		
	// do not allow it this time
	HostName hostName = new HostName("23.23.43", hostParams);
	check(hostName);
		
	// otherwise works ok
	hostName = new HostName("23.23.43");
	check(hostName);
		
	// or make it default behaviour using fixed params
	class MyHostNameClass extends HostName {
		MyHostNameClass(String name) {
			super(name, hostParams);
		}
	}
	hostName = new MyHostNameClass("23.23.43");
	check(hostName);

with this method:

	static void check(HostName hostName) {
		try {
			System.out.println("host name: " + hostName.getHost());
			hostName.validate();
		} catch (HostNameException e) {
			System.out.println(e.getMessage());
		}
		System.out.println();
	}

Output:

    host name: null
    23.23.43 Host error: invalid host

    host name: 23.23.0.43

    host name: null
    23.23.43 Host error: invalid host

**Comment by alperenp** [comment]
Thanks for your explanation and assistance about the library.

I wish you best,
Alperen
