### ISSUE TITLE
How can i get the ip class? from a IPAddress 

### ISSUE THREAD

**Issue by lohxx** [seancfoley/IPAddress#21]
code:
```java
IPAddress address = new IPAddressString(ip).getAddress();
IPAddress mask = address.getNetwork().getNetworkMask(16, false);
IPAddressSection network;
network = address.getNetworkSection(16, true);
BigInteger range = address.getSequentialBlockCount();
```

**Comment by seancfoley** [comment]
I am not entirely certain what you are asking.  

Are you asking about IPv4 address classes as describer here: https://www.sqa.org.uk/e-learning/WebTech01CD/page_11.htm ?

Are you talking about converting to the IPv4Address or IPv6Address instance from an instance of IPAddress?

getSequentialBlockCount() is probably not what you want, it is used for counting the number of sequential series of addresses in a given subnet.  In an address like 1.2-10.0.0/16, the sequential block count is 1 because the addresses in the subnet are sequential (consecutive).   In an address like 1.2-10.0.3-4, the sequential block count is 9: 1.2.0.3-4/16, 1.3.0.3-4/16, ..., 1.10.0.3-4/16.

**Comment by lohxx** [comment]
Yeah, I AM talking about the IP classes described in the link.

**Comment by lohxx** [comment]
Is there any way to get this info with your library?

**Comment by seancfoley** [comment]
Use this:

    public static String getIPv4Class(String ipaddressStr) {
		IPAddressString addressStr = new IPAddressString(ipaddressStr);
		IPAddress address = addressStr.getAddress();
		if(address != null && address.isIPv4()) {
			IPv4Address addr = address.toIPv4();
			IPv4AddressSegment firstSeg = addr.getSegment(0);
			int value = firstSeg.getSegmentValue();
			if(value < 128) {
				return "A";
			} else if(value < 192) {
				return "B";
			} else if(value < 224) {
				return "C";
			} else if(value < 240) {
				return "D";
			}
			return "E";
		}
		return "none";
	}

Examples: 

    public static void main(String[] args) {
		checkAddress("::1");
		checkAddress("1.2.3.4");
		checkAddress("155.2.3.4");
		checkAddress("200.2.3.4");
		checkAddress("225.2.3.4");
		checkAddress("241.2.3.4");
	}
	
	public static void checkAddress(String ipaddressStr) {
		System.out.println(getIPv4Class(ipaddressStr));
	}

output:

    none
    A
    B
    C
    D
    E

**Comment by lohxx** [comment]
Okay! thanks
