### ISSUE TITLE
Hex IPv4 address NOT understood as IPv4

### ISSUE THREAD

**Issue by oomphfortuity** [seancfoley/IPAddress#22]
I have hex 000000000000000000000000C0A80000 IPV4 address . Its decimal form is 192.168.0.0. I do want to check whether hex ip is of type IPV4 or IPV6.

isIPv4() is returning FALSE for above IPV4 address and saying it as IPV6.
```
new IPAddressString("000000000000000000000000C0A80000").getAddress().isIPv6() //true
new IPAddressString("000000000000000000000000C0A80000").getAddress().isIPv4() //false
```

I think leading zeros creating issue. Because of leading zeros it is exceeding length of standard IPv4 length hence it is giving it as IPv6.

**Comment by seancfoley** [comment]
That is not a hex ipv4 address.  IPv4 addresses are 32 bits, so that is 8 hex characters at most.  A 32 hex character string is 128 bits, the length of IPv6, so is considered to be IPv6.  

If it does not have 32 total digits (or 20 total digits which is considered base 85), and it has 11 or less non-zero digits then it will be considered IPv4.  However, for hex it must have the format specified by inet_aton (see issue 19), which means it must have 0x prepended, otherwise it is expected to be base 10.  If it has a leading zeros it is considered octal.

		IPAddress addr = new IPAddressString("000000000000000000000000C0A80000").getAddress(); // 32 chars, so IPv6
		IPAddress addr2 = new IPAddressString("0x000000000000000000000000C0A80000").getAddress(); // 0x for hex is allowed as well
		IPAddress addr3 = new IPAddressString("0x00000000000000000000000C0A80000").getAddress(); // less than 32 total digits and less then 12 non-zero digits, so IPv4
		IPAddress addr4 = new IPAddressString("00000000000000000000000C0A80000").getAddress(); // No 0x, so cannot be ipv4 hex, interpreted as decimal, and it is not decimal
		IPAddress addr5 = new IPAddressString("0xC0A80000").getAddress(); // proper hex ipv4 length
		IPAddress addr6 = new IPAddressString("C0A80000").getAddress(); // No leading zero means decimal, but address not decimal
		IPAddress addr7 = new IPAddressString("80880000").getAddress(); // No leading zero means decimal
		IPAddress addr8 = new IPAddressString("0C0A80000").getAddress(); // leading 0 means octal, but address not octal
		IPAddress addr9 = new IPAddressString("070770000").getAddress(); // leading 0 means octal
		System.out.println(addr);
		System.out.println(addr2);
		System.out.println(addr3);
		System.out.println(addr4);
		System.out.println(addr5);
		System.out.println(addr6);
		System.out.println(addr7);
		System.out.println(addr8);
		System.out.println(addr9);

output:

    ::c0a8:0
    ::c0a8:0
    192.168.0.0
    null
    192.168.0.0
    null
    4.210.33.128
    null
    0.227.240.0

**Comment by oomphfortuity** [comment]
I understood that by shortening the hex , we can get desired result.  

 ```
private static String toShortHex(String ip){
        if ((ip = ip.toUpperCase()).startsWith("0X")) {
            ip = ip.replace("0X", "");
        }
        String shortHex = new BigInteger(ip, 16).toString(16);
        return (shortHex.length () % 2 == 0 ? "0x" : "0x0") + shortHex;
  }
```

My advise should be that it would be better if this is part of API itself.

**Comment by seancfoley** [comment]
Well, since a 32 bit IPv4 address is at most 8 hex characters, I don't know why you would have all those zeros stuck on the front anyway.  There is no reason to be using 32 characters for IPv4 with all those zeros stuck on the front.  That is why it is not considered IPv4 automatically: IPv4 is at most 8 hex digits.

**Comment by oomphfortuity** [comment]
You are right. But tools like excel or csv add these extra zeros in hex.

**Comment by seancfoley** [comment]
OK, so in summary, the IPAddressString class parses both IPv4 and IPv6 and attempts to resolve ambiguities itself.  In this case, the string matched the exact length of hex IPv6 so was interpreted as IPv6.  

All cases of ambiguity involve plain numbers (ie nothing with segment separators like ':' or '.' that are clearly one or the other).  So if you have a plain number, and you do not want IPAddressString to make the decision on the ambiguous string because you already know the number is IPv4, then use any one of the 3 examples in https://github.com/seancfoley/IPAddress/issues/23 to parse the number first and then construct the IPv4 address.

The three examples show how use [Integer.parseInt](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#parseInt-java.lang.String-int-) and [construct IPv4Address from int](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4Address.html#IPv4Address-int-), use [BigInteger constructor](https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#BigInteger-java.lang.String-int-) and [method toByteArray](https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#toByteArray--) and [construct IPv4Address from byte array](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4Address.html#IPv4Address-byte:A-) or call [IPAddressGenerator.from](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressNetwork.IPAddressGenerator.html#from-byte:A-) with the byte array obtained from BigInteger.

If you do wish to use one of those solutions and you really wish to use only IPAddressString, then you can easily make the string into a string that IPAddressString will interpret as IPv4.  For hex numbers, this means chopping off the leading zeros so that is becomes 8 characters and then prepending a "0x".  At that point IPAddressString will parse as IPv4.
