### ISSUE TITLE
Methods isValid() & isIPv4() failed to recognise invalid IP address 

### ISSUE THREAD

**Issue by oomphfortuity** [seancfoley/IPAddress#24]
I am trying to validate IP address for further processing.

IPAddressString() & IPAddress() both are failing to recognise invalid ip string.
 
```
 IPAddressString ipstr = new IPAddressString("-");
 ipstr.isValid() //true
 ipstr.isIPv4()  //true
```

I think this.validate() is throwing error

> Method threw 'java.lang.StackOverflowError' exception

.

**Comment by seancfoley** [comment]
Perhaps it is surprising, but that is actually intended behavior.

Keep in mind that the default behaviour regarding what formats are supported is permissive, to allow all address formats supported by the library. 

That string is something the library supports.

In a given string, if there is no segment separator like ‘.’ or ‘:’, then it is recognized as either a single value (like 1) or range of values (like 1-10).  Whether it is IPv4 or IPv6 is decided by the number of characters.  For a single value, 32 characters denote hex IPv6, 20 characters indicate base 85 IPv6, and if 11 characters or less, excluding leading zeros, then it is considered IPv4.  The ‘-‘ character denotes a range and for ranges we expect double the number of characters as listed above.  

When there is a range with one or two values missing, the missing value is inferred to be the lowest or highest potential segment values for that address type, depending on whether it is on the left or right side, respectively (this is something that actually matches the behavior of the popular tool nmap).  The lowest possible value is always 0.  The highest possible value is the highest value for a single segment, which is 255 for IPv4.

So '-' this is interpreted as an address range that is IPv4, a range with both range values missing, which are therefore interpreted as 0 and 255.  So that means that the address - is the same as 0-255 which is the same is 0.0.0.0-255 which is the same as 0.0.0.*, and that is what you get as the string when you print the address.

Understandably, it is not obvious that's what you'd get for an address when specifying '-'.

If you wish to disallow that string, there are means to do so, using IPAddressStringParameters, which allows you to be more specific about what you wish to allow, as shown in the following code:

	IPAddressString ipstr = new IPAddressString("-");
	System.out.println(ipstr.isValid()); // true
	System.out.println(ipstr.isIPv4()); // true 
	System.out.println(ipstr.getAddress()); // 0.0.0.*

	IPAddressStringParameters params = new IPAddressStringParameters.Builder().
		allowSingleSegment(false).toParams(); // no single valued addresses
	ipstr = new IPAddressString("-", params);
	System.out.println(ipstr.isValid()); // false
	System.out.println(ipstr.isIPv4()); // false
	System.out.println(ipstr.getAddress()); // null
		 
	params = new IPAddressStringParameters.Builder().setRangeOptions(RangeParameters.NO_RANGE).toParams();
	ipstr = new IPAddressString("-", params); // don't allow ranges of values
	System.out.println(ipstr.isValid()); // false
	System.out.println(ipstr.isIPv4()); // false
	System.out.println(ipstr.getAddress()); // null

When using your own IPAddressStringParameters, it can be useful to use your own factory method or your own subclass:

	static final IPAddressStringParameters params = new IPAddressStringParameters.Builder().allowSingleSegment(false).toParams();
	
	static class MyIPAddressString extends IPAddressString {
		MyIPAddressString(String str) {
			super(str, params);
		}
	}
	
	static IPAddressString factoryMethod(String str) {
		return new IPAddressString(str, params);
	}

Then:

	IPAddressString str = new MyIPAddressString("-");
	IPAddressString str2 = factoryMethod("-");

I am also thinking about adding a new parameter to disallow the inferred values for missing ranges, which will be another way to control this behaviour.

**Comment by seancfoley** [comment]
BTW, I have not seen any StackOverflowErrors anywhere, so you'd have to provide a test case or a stack trace.

**Comment by oomphfortuity** [comment]
It was issue in my setup. I had resolved that StackOverflowError.

"-" is considered as Range & hence IPv4. It seems fair to me. Thanks
