### ISSUE TITLE
getHostAddress() should belong to IPAddress, not IPAddressString

### ISSUE THREAD

**Issue by mkpaz** [seancfoley/IPAddress#28]
1 - It loses concrete type after conversion: 

```java
IPv4Address ip = new IPv4Address(123456, 24);
ip.toAddressString().getHostAddress().isPrivate(); // oops
```
2 - It's unnecessary conversion that just spoils the code and also leads to unexpected behavior

```java
// should work, but don't
ip.getNetwork().getNetworkMask(ip.getPrefixLength()).toAddressString().getHostAddress();
// looks ugly, but works
ip.getNetwork().getNetworkMask(ip.getPrefixLength()).removePrefixLength();
```

**Comment by seancfoley** [comment]
Firstly, _toAddressString()_ is a method that was added to get the original object used to parse the address, which may be useful in some circumstances (storage of parser/unparsed in collections, for instance), but generally not for manipulation of addresses.  Generally, once you have an IPAddress you do not need to go back to IPAddressString.

_getHostAddress()_ was added to IPAddressString, following the request in issue 3, to ignore prefix/mask when parsing to an IPAddress from a String.  Since then, there are now other ways to do the same, but there was not back then.  I have not removed the method, nor changed the name, to maintain backwards compatibility.  But the method _getHostAddress()_ is redundant and really unnecessary now.

So the use-case you've presented here is not something I would have expected for getHostAddress().  It is the result of the two independent additions above.  I suppose that as more methods are added to IPAddressString, this might result in similar confusion.  But the general rule is that IPAddressString has methods that operate on the original string.  If there never was an original string, as in your example, then it should be consistent with whatever equivalent methods exist in IPAddress, but in this case it is not, so I can make a change to fix that, that does seem to have been missed along the way as the above two additions (getHostAddress and toAddressString) were made.  I can also make a change to the javadoc for IPAddressString to clarify what I am saying here.

Anyway...

The intended methods for getting network are IPAddress.toNetworkAddress/toZeroHost. The deprecated removePrefixLength will do the same but will also remove the prefix length.

The intended method for getting host (ie removing prefix length) is IPAddress.withoutPrefixLength(), which was added to remove potential confusion around removePrefixLength.  If you also wanted to make the network bits zero, you'd have to call mask() with the host mask (which can be obtained by ip.getNetwork().getHostMask(ip.getPrefixLength()).  Looks to me like there is no method to do this directly, but I am not sure if it deserves such a method.  And that does not appear to be what you want anyway.

I think what you want is IPAddress.withoutPrefixLength().

**Comment by mkpaz** [comment]
Much tnx for the explanation! `withoutPrefixLength()` is exactly what i need. The intention though was much simpler. I've tried to find a way to print the host part of the address, but it seems that all variety of `to***String()` methods doesn't provide such option, so I've found the issue you mentioned about and thought `getHostAddress()` is the only way to go.

**Comment by seancfoley** [comment]
Yes, there is no to***String() option for that.

To print just the host part of the address 1.2.3.4/16:
1. I really did not have an analogous function for IPAddress.toZeroHost/IPv4Address.toNetworkAddress, and it seems it could be useful, up to now most functions just operate on the host, so I am adding the corresponding IPAddress.toZeroNetwork which will zero-out the network bits.  
In the meantime, to get the same thing you can do:
		IPv4Address addr = new IPAddressString("1.2.3.4/16").toAddress().toIPv4();
		IPv4Address host = addr.mask(addr.getNetwork().getHostMask(addr.getNetworkPrefixLength())); // new method getHostMask() will do this too
		System.out.println(host); // 0.0.3.4

2. Another thing you can do is just get the host section:

		IPv4AddressSection hostSection = addr.getHostSection(addr.getNetworkPrefixLength()); 
		System.out.println(hostSection); // 3.4
