### ISSUE TITLE
Crash in android when using R8 (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by polaris0227** [seancfoley/IPAddress#29]
`java.lang.NoClassDefFoundError: f.a.b.ka
        at inet.ipaddr.ipv4.IPv4AddressSection.<init>(IPv4AddressSection.java:17)`

Proguard needed.
Please help.
Thanks.

**Comment by seancfoley** [comment]
More information is needed, you'll need to explain what you're doing.  Looks like you've used a tool to modify bytecode, possibly proguard?  If so, it looks like the tool has renamed some class and your new jar does not have that class in it.  You should check to see you are including this new class file (/f/a/b/ka.class) in whatever archive you are using with your code.  

Almost certainly this is not an issue with IPAddress, but if you provide more info maybe I can provide suggestions.

**Comment by polaris0227** [comment]
Thanks for your reply.
I'm using your library for my android app and it is shrinked by R8 for
release.
Unfortunately app is crashed in your library at the line 147 of
IPv4AddressSection.
setPrefixedSegments(
      network,
      networkPrefixLength,
      getSegmentsInternal(),
      IPv4Address.BITS_PER_SEGMENT,
      IPv4Address.BYTES_PER_SEGMENT,
      network.getAddressCreator(),
      !singleOnly && isPrefixSubnet(segments, networkPrefixLength, network,
false) ?* IPv4AddressSegment::toNetworkSegment :
IPv4AddressSegment::toPrefixedSegment*);

Hope this helps for fixing issue.
Thanks again.

**Comment by seancfoley** [comment]
Looks like a problem with R8.  NoClassDefFoundError means that a class cannot be found, loaded, or initialized.  If that is the line, then It would have to be IPv4Address or IPv4AddressSegment.  

It is probably IPv4AddressSegment.  It has probably renamed inet.ipaddr.ipv4.IPv4AddressSegment to f.a.b.ka.  It probably doesn't work automatically with Java 8 method references like IPv4AddressSegment::toNetworkSegment.

First you should try to stop it from renaming.
https://r8-docs.preemptive.com/
Use this rule:
-dontobfuscate

Then, if that worked, you can try to be more specific with rules like:
-keepnames class inet.ipaddr.ipv4.IPv4AddressSegment

**Comment by seancfoley** [comment]
https://stackoverflow.com/questions/57766218/how-to-add-r8-rules-in-android

**Comment by seancfoley** [comment]
https://stackoverflow.com/questions/45976225/how-to-write-rules-for-proguard

**Comment by polaris0227** [comment]
Thank you for your response.
But it doesn't work.

**Comment by seancfoley** [comment]
The docs are here: https://developer.android.com/studio/build/shrink-code#enable
Start by disabling all those operations: shrinking, obfuscation, optimizing.  Then enable them, one by one, to determine which one is the culprit.  Then add rules to restrict that particular operation until you can make it work.  As the docs indicate, such tools "might introduce bugs if you do not sufficiently customize which code to keep".  So that is what has happened here, you have not sufficiently customized which code to keep.  Since this depends on what exactly your app is doing, it is not something I can explicitly do for you.

**Comment by seancfoley** [comment]
I tried this out back in November, I tried the default minify, shrinking and obfuscation when building in Android Studio, with a simple app using IPAddress, and it did not seem to work, like you said.  When disabling those options, the building, installing and running the app worked fine.  So I intended to look into it (even though it's not an issue with this library).  Since then I installed a newer version of Android Studio, and it appears to work fine.  So I am assuming the latest Android Studio has fixed whatever issues were involved.  Closing this issue.
