### ISSUE TITLE
extract ip from mixed ip/mask specification

### ISSUE THREAD

**Issue by pottedplant** [seancfoley/IPAddress#3]
```
IPAddressString ipas = new IPAddressString("10.1.2.3/24");
ipas.getAddress(); // returns "10.1.2.0"
```
Is there a way to retrieve the "original/unmasked" ip address?
```ipas.getUnmaskedAddress() -> "10.1.2.3"```

I would like to parse strings representing a ip/mask combination.
Maybe I'm missing something.

**Comment by seancfoley** [comment]
That's a good question, it's something I had thought about before.

Generally, 10.1.2.3/24 may denote the single, distinct interface address 10.1.2.3, or the the IPv4 block of 255 addresses which includes 10.1.2.3 (although you're right that the block would be usually denoted 10.1.2.0/24)

I decided that for this library I would make 10.1.2.3/24 represent the IPv4 block (subnet) rather than making it equivalent to just the single address 10.1.2.3 paired with its prefix length of 24.
I did not want to have the inconsistency where  10.1.2.3/24 would be a single address and 10.1.2.0/24 would be a set of 255 addresses.

Anyway, like you said, there are cases when you'd want to extract the original individual address paired with the prefix, even if you threw out the prefix afterward - you'd still want to parse and extract the address in some cases.

So I am adding a method for that, I will have it in there in a day or two, should not take long, I think it will be named IPAddressString::getHostAddress

**Comment by pottedplant** [comment]
Wonderful, getHostAddress sounds good. A lot less complicated than my getUnmaskedAddress . Thank you for your great work.

**Comment by seancfoley** [comment]
Hi, you're welcome, and I appreciate the feedback.  

I've checked in the change to the v2 branch, I've added IPAddressString::getHostAddress to v2 branch which at this time is the branch with the latest release.  At this time, the only difference between master branch and v2 is this addition.  The jar has been updated here:
 https://github.com/seancfoley/IPAddress/tree/v2/IPAddress/dist

I'll release this as version 2.0.2 in a short time.

This was added to v2 only because master will be getting much bigger changes (for a v3) in a short time, Those changes will include this change as well.
