### ISSUE TITLE
Ipv6 address subnet

### ISSUE THREAD

**Issue by marcoberri** [seancfoley/IPAddress#34]
hi, i have an ipv6 subnet, and i have to get the list of addresses of the subnets contained.
In this case I get only one value but in reality I should get more (ex: 2a03:b7c0:230:33::/64 , 2a03:b7c0:230:34::/64, etc.).
it's correct?
thank you

```
     IPAddress subnet = new IPAddressString("2a03:b7c0:0230:0033::").getAddress();
        subnet = subnet.setPrefixLength(53);
        IPAddress newSubnets = subnet.setPrefixLength(64, false);
        Iterator<? extends IPAddress> iterator = newSubnets.prefixBlockIterator();
        while (iterator.hasNext()) {
            system.out.print(iterator.next().toInetAddress().getHostAddress());
        }
```

**Comment by seancfoley** [comment]
Hello, in your code you set the prefix length to 64 from 53 and since you have an all-zero host for the /64 subnet, this does create a /64 prefix block, as shown by adding this line:
```java
 System.out.println(newSubnets + " count is " + newSubnets.getCount());
```
```
2a03:b7c0:230:33::/64 count is 18446744073709551616
```
However, there is only one prefix at that point, "2a03:b7c0:230:33", so the prefix block iterator will give you just that one, the one block "2a03:b7c0:230:33::/64".  

Not sure exactly, but it looks to me like perhaps you want to get all the prefixes when changing the bits from bit index 53 to 64 to all possible value, which is all the /64 subnets of 2a03:b7c0:230::/53.

There is more than one way to do that.  One thing you can do when adding to your code, is to zero out the bits from 64 to 53 when creating the /53 subnet, by giving the original address a /64 prefix length to start, since the default behavior of setPrefixLength is to zero out bits between new and old prefix lengths:
```java
IPAddress subnet = new IPAddressString("2a03:b7c0:0230:0033::").getAddress();
subnet = subnet.setPrefixLength(64);
subnet = subnet.setPrefixLength(53);
IPAddress newSubnets = subnet.setPrefixLength(64, false);
System.out.println("prefix count is " + newSubnets.getPrefixCount() + " from " + 
    newSubnets.getLower().toPrefixBlock() + " to " + 
    newSubnets.getUpper().toPrefixBlock());
```
However, the simpler approach is to just create that block directly, you can always call toPrefixBlock() for any subnet to get the block:
```java
IPAddress subnet = new IPAddressString("2a03:b7c0:0230:0033::").getAddress();
subnet = subnet.setPrefixLength(53).toPrefixBlock();
IPAddress newSubnets = subnet.setPrefixLength(64, false);
System.out.println("prefix count is " + newSubnets.getPrefixCount() + " from " + 
    newSubnets.getLower().toPrefixBlock() + " to " + 
    newSubnets.getUpper().toPrefixBlock());
```
Or even starting with the original string:
```java
IPAddress subnet = 
    new IPAddressString("2a03:b7c0:0230:0033::/53").getAddress().toPrefixBlock();
IPAddress newSubnets = subnet.setPrefixLength(64, false);
System.out.println("prefix count is " + newSubnets.getPrefixCount() + " from " + 
    newSubnets.getLower().toPrefixBlock() + " to " + 
    newSubnets.getUpper().toPrefixBlock());
```
The output in all 3 cases is 
```
prefix count is 2048 from 2a03:b7c0:230::/64 to 2a03:b7c0:230:7ff::/64
```
So when you get the prefix block iterator, you will iterate through those 2048 block addresses.
