### ISSUE TITLE
How IPAddressString parse a IP range？

### ISSUE THREAD

**Issue by MingNiu** [seancfoley/IPAddress#5]
for example:
start ip is 10.100.100.50
end ip is 10.100.101.50

**Comment by seancfoley** [comment]
Hello,

It depends on what you mean by:
start ip is 10.100.100.50
end ip is 10.100.101.50

That could mean 
(a) just the two addresses 0.100.100.50 and 10.100.101.50, or 
(b) the range of 257 addresses 10.100.100.50, 10.100.100.51, 10.100.100.52, ..., 10.100.100.255, 10.100.101.0, 10.100.101.1, ...,  0.100.101.50

For subnets you can use either the range separator character ‘-‘ or the standard prefix length notation ‘/‘

If you want (a), then you can use new IPAddressString("10.100.100-101.50”), since the range char ‘-‘ applies only to the third segment.  You cannot represent (a) with prefix length notation (1.2.3.0/24) since the two values are not consecutive.

If you want (b), when using range notation, you need to split it up so that the partial ranges (0-50 and 50-255) apply only to the lowest segment, which means you need two addresses: new IPAddressString("10.100.100.50-255“) and new IPAddressString("10.100.101.0-50”).  

When using prefix length notation, which is the usual manner of representing address ranges, there is a helper method to give you the minimal set of prefix length subnets to cover that same range, spanWithPrefixBlocks. For example:

		IPAddressString lower = new IPAddressString("10.100.100.50");
		IPAddressString upper = new IPAddressString("10.100.101.50");
		IPAddress lowerAddress = lower.getAddress();
		IPAddress upperAddress = upper.getAddress();
		IPAddress subnets[] = lowerAddress.spanWithPrefixBlocks(upperAddress);
		for(IPAddress subnet: subnets) {
			System.out.println(subnet);
		} 


 Output:

10.100.100.50/31
10.100.100.52/30
10.100.100.56/29
10.100.100.64/26
10.100.100.128/25
10.100.101.0/27
10.100.101.32/28
10.100.101.48/31
10.100.101.50

Counting these from top to bottom you have the 2 + 4 + 8 + 64 + 128 + 32 + 16 + 2 + 1 = 257 addresses spanning from 10.100.100.50 to 0.100.101.50 in order.  This is the minimal set to cover the range.

**Comment by MingNiu** [comment]
Thanks for your reply!

I feel this is a more direct and clear way of expression：
https://github.com/jgonian/commons-ip-math

Ipv4 start = Ipv4.of("10.100.100.50");
Ipv4 end = Ipv4.of("10.100.101.50");
Ipv4Range a = Ipv4Range.from(start).to(end);

**Comment by seancfoley** [comment]
OK, so now I understand what you are looking for.

This library does not have a data type in which Address objects encapsulate other Address objects, like the IPv4Range class of that library, however it's not hard to write a range class that would be equivalent to that Ipv4Range class, something that would be constructed by supplying two Address objects.  I'll consider whether it would be useful to add that or not.  

This library constructs address objects that can be represented by a single string expression, either using ranges of segments, or using prefix lengths.

As mentioned, this library supports ranges but they are per segment.  Also, with this library there are classes that allow different segment/division sizes.  So you can do this:

		IPAddressString lower = new IPAddressString("10.100.100.50");
		IPAddressString upper = new IPAddressString("10.100.101.50");
		IPv4Address lowerAddress = lower.getAddress().toIPv4();
		IPv4Address upperAddress = upper.getAddress().toIPv4();
		// reconstitute as a grouping of a single segment
		IPAddressBitsDivision one = new IPAddressBitsDivision(lowerAddress.longValue(), upperAddress.upperLongValue(), IPv4Address.BIT_COUNT, IPv4Address.DEFAULT_TEXTUAL_RADIX);
		IPAddressDivisionGrouping grouping = new IPAddressDivisionGrouping(new IPAddressDivision[] {one}, lowerAddress.getNetwork());
		System.out.println(grouping);

output:

    [174351410-174351666]

This is not exactly the same but similar, it represents the same range of addresses as your example.

**Comment by seancfoley** [comment]
In version 5.0.0 I have added the class IPAddressSeqRange and subclasses IPv4AddressSeqRange and IPv6AddressSeqRange.  Those classes provide the full functionality described herein.
