### ISSUE TITLE
Iterate over network interfaces 

### ISSUE THREAD

**Issue by QIvan** [seancfoley/IPAddress#52]
hi! first of all, thank you for your wonderful API, you rock! =) 

I didn't find a "native" way how to iterate over network interfaces for a box. 
I came up with a code like 

```java 
IPAddressGenerator generator = new IPAddressGenerator();

List<IPAddress> interfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
        .stream()
        .flatMap(ni -> Collections.list(ni.getInetAddresses()).stream())
        .map(generator::from)
        .collect(Collectors.toList());
```

but it looks overkill for me. Do you have a simpler way? 
thanks!

**Comment by QIvan** [comment]
if to be more specific: 
I need to look up the ip address of the box with a specific mask like 
for `127.0.0.0/8` the localhost should be found. 

I make this code 

```
IPAddressGenerator generator = new IPAddressGenerator();

IPAddress ourIpAddress = Collections.list(NetworkInterface.getNetworkInterfaces())
        .stream()
        .flatMap(ni -> Collections.list(ni.getInetAddresses()).stream())
        .map(generator::from)
        .filter(other -> subnet.contains(other.toAddressString()))
        .findFirst()
        .orElseThrow(IllegalArgumentException::new);
```

but once again, it looks too complicated and, presumably, there should be a simpler way for such great library like this one. Didn't I just find hard enough? 
Thanks!

**Comment by QIvan** [comment]
hi, @seancfoley 
maybe you have any thoughts on this? 
thanks in advance!

**Comment by seancfoley** [comment]
The first part of your question is more of a general Java question than an IPAddress question.  IPAddress doesn't have any functionality that covers the functionality in NetworkInterface.

When using streams, I think flatMap is the right approach,  it is recommended for "flattening" out nested collections or arrays into a single stream.  Streams are better suited for large collections, since they have some overhead.  Also, since Enumeration does not provide a size ahead of time, converting them to streams is sometimes inefficient.
  
In this case, the number of addresses is small, there is likely a small number of interfaces and likely one or two addresses per interface on a typical machine.
	 
For the simplest code, you can use just iterators with lambdas.

	List<IPAddress> interfaceAddrs = new ArrayList<>();
	NetworkInterface.getNetworkInterfaces().asIterator().
		 forEachRemaining(ni -> ni.getInetAddresses().asIterator().
		 		forEachRemaining(addr -> interfaceAddrs.add(generator.from(addr))));

Or if you're looking for the best performance, use a double loop.

	List<IPAddress> interfaceAddrs2 = new ArrayList<>();
	Enumeration<NetworkInterface> nis = NetworkInterface.getNetworkInterfaces();
	while(nis.hasMoreElements()) {
		Enumeration<InetAddress> addrs = nis.nextElement().getInetAddresses();
		while(addrs.hasMoreElements()) {
			interfaceAddrs2.add(generator.from(addrs.nextElement()));
		}
	}

These two blocks of code do the same thing as your first block of code but are more efficient.

Then, once you have a list, you can convert that to a stream as in your second block.  But once you are working with IPAddress instances, don't go back to IPAddressString.

	IPAddress allIPv4Addresses = new IPAddressString("*.*").getAddress();
	System.out.println(allIPv4Addresses);
	IPAddress containedIPv4 = interfaceAddrs2.stream().filter(other -> allIPv4Addresses.contains(other))
		.findFirst()
	        .orElseThrow(IllegalArgumentException::new);
	System.out.println(containedIPv4);
		 
	IPAddress allIPv6Addresses = new IPAddressString("*:*").getAddress();
	System.out.println(allIPv6Addresses);
	IPAddress containedIPv6 = interfaceAddrs2.stream().filter(other -> allIPv6Addresses.contains(other))
		.findFirst()
		.orElseThrow(IllegalArgumentException::new);
	System.out.println(containedIPv6);

One again, streams are not necessary though, since this is a small number of addresses, you could just loop through them.  If you have a large number of addresses to check, then [using a trie](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#select-addresses-contained-by-a-cidr-prefix-block-subnet) is more efficient.  However, when using a trie, you would lose the ordering of your network interface addresses, so you might want just a loop since the ordering can matter with network interfaces.

	IPAddress foundIPv4 = null, foundIPv6 = null;
	for(IPAddress addr: interfaceAddrs) {
		if(foundIPv4 == null && allIPv4Addresses.contains(addr)) {
			foundIPv4 = addr;
			if(foundIPv6 != null) {
				break;
			}
		}
		if(foundIPv6 == null && allIPv6Addresses.contains(addr)) {
			foundIPv6 = addr;
			if(foundIPv4 != null) {
				break;
			}
		}
	}
	System.out.println(foundIPv4);
	System.out.println(foundIPv6);

**Comment by seancfoley** [comment]
In summary, if it were me, I would do this:

	List<IPAddress> interfaceAddrs = new ArrayList<>();
	NetworkInterface.getNetworkInterfaces().asIterator().
		forEachRemaining(ni -> ni.getInetAddresses().asIterator().
			forEachRemaining(addr -> interfaceAddrs.add(generator.from(addr))));
	IPAddress found = null;
	for(IPAddress addr: interfaceAddrs) {
		 if(subnet.contains(addr)) {
		 	found = addr;
		 	break;
		 }
	}
	System.out.println(found);

**Comment by QIvan** [comment]
wow! cool, thank you a lot for this very detailed answer! 

Do you think it might be a good idea to add a similar method to the library? 
I can imagine a lot of people are looking for to get a list of interfaces with a better API, rather than the standard `NetworkInterface.getNetworkInterfaces()`

**Comment by seancfoley** [comment]
Most of this library provides functionality that is absent from the Java standard library and also absent from other available libraries like Guava, those from Apache, and so on, which was the primary motivation to write it.  The Python language had something similar, but most Java libraries were insufficient for my desires, and this library goes beyond what is provided by the Python library.  

I am not so sure I could do the same for network interfaces, whether there is much I could add to the existing APIs for network interfaces.  This specific issue is one thing but in the end it's just 10 lines of code, so I might add it to the wiki.  

Thanks for the suggestion, I'll give it some thought.
