### ISSUE TITLE
CIDR address generation question

### ISSUE THREAD

**Issue by psparago** [seancfoley/IPAddress#53]
I am very new to IPAddress and find it an impressive and comprehensive library.

I'm running into an issue generating IPs from a CIDR. IPAddress does not consider 10.90.6.14/30 a CIDR and addr.isMultiple() returns false.

Our legacy code (Golang) and a couple of online CIDR calculators I've tried return:

10.90.6.12 10.90.6.13 10.90.6.14 10.90.6.15

Can anyone advise me on how to achieve this result using the IPAddress library?

**Comment by seancfoley** [comment]
This is similar to issues #26, issue #30,  issue #39, issue #45, and issue #51.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#parse-prefixed-ip-address-string-as-subnet-or-ip-address) and this [entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#check-if-subnet-contains-address-or-subnet) - see enclosingBlockContains() in particular.

In summary, 
10.90.6.14/30 is the same as 10.90.6.14 because the host is not zero.  10.90.6.12/30 is the subnet of 4 addresses because the host is zero.  If you want to convert to the subnet, then use toPrefixBlock.
```java
list(new IPAddressString("10.90.6.12/30").getAddress());	
list(new IPAddressString("10.90.6.14/30").getAddress().toPrefixBlock());

static void list(IPAddress addr) {
	System.out.println(addr + " has count " + addr.getCount());
	for(IPAddress addr2 : addr.getIterable()) {
		System.out.println(addr2);
	}
	System.out.println();
}
```
Output:
```
10.90.6.12/30 has count 4
10.90.6.12/30
10.90.6.13/30
10.90.6.14/30
10.90.6.15/30

10.90.6.12/30 has count 4
10.90.6.12/30
10.90.6.13/30
10.90.6.14/30
10.90.6.15/30
```
