### ISSUE TITLE
Hope to add a function to determine whether the address belongs to a CIDR-like block whatever host bit is not zero. 

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#55]
Currently, [[Containment within a CIDR prefix block]](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#containment-within-a-cidr-prefix-block) function can judge whether the address belongs to the CIDR block, but sometimes the host bit of a given CIDR block is not zero, which will cause the function to judge the failure.

Hope to add a function to determine whether the address belongs to a CIDR-like block whatever host bit is not zero.

**Comment by seancfoley** [comment]
If the host bit is not zero, use [toPrefixBlock() to get the CIDR block](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#containment-within-the-enclosing-cidr-prefix-block):

    boolean contains = new IPAddressString("1.2.0.1/16").getAddress().toPrefixBlock().contains(
        new IPAddressString("1.2.3.4").getAddress()); // true

or just [ignore the host](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#comparing-just-the-prefix):

	contains = new IPAddressString("1.2.0.1/16").prefixContains( new IPAddressString("1.2.3.4")); // true
		
	contains = new IPAddressString("1.2.0.1/16").prefixEquals(new IPAddressString("1.2.3.4")); // true

**Comment by angelyouyou** [comment]
@seancfoley 
Thank you for your reply. What is the current performance of querying whether a single IP address belongs to a certain network segment? Is there performance test data?

**Comment by seancfoley** [comment]
Performance is relative.   It depends on the processor, RAM, and many other elements of the platform you are running on.  It also depends on which of the above containment methods is used.  It also depends on whether starting from strings or not.  It also depends on the format of string input, since IPAddress supports many different input formats, and in some cases just looking at the string can determine containment, while in other cases it is less simple.

For basic string cidr containment, it has been compared to other libraries here: https://stackoverflow.com/a/54049313/6801443
