### ISSUE TITLE
It is hoped to provide an interface or capability, which can increase the storage of custom information in the add and elementsContainedBy functions of IPv4AddressTrie. 

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#58]
A typical scenario that requires search performance is:
In a frequent call (for example, when a large number of packets are received), the subnet to which it belongs and the custom information (such as groups, etc.) that the subnet belongs to will be queried through the IP address. Currently, the subnet to which the subnet belongs can be found relatively quickly through IPv4AddressTrie, but the custom information to which the subnet belongs cannot be found directly. It is necessary to establish the relationship between the custom information and the subnet again and perform a second search.
The coding logic that users need to perform is:
1. Pre-built data
a. Establish IPv4AddressTrie tree in advance;
b. Establish the relationship between custom information (such as a group) and IPv4TrieNode.

2. Receive a packet with the specified destination IP
a. Find the subnet to which it belongs through the destination IP (IPv4TrieNode);
b. Search the custom information to which it belongs through the subnet (IPv4TrieNode) twice.

Business scenario example: A packet with a destination address of 30.1.1.2 is received, and the group information to which it belongs is searched.
Group 1:
1.1.1.1/24
2.2.2.2/24
3.3.3.3/32
...

Group 2:
10.1.1.1/16
20.1.1.1/24
30.1.1.1/32

Therefore, it is hoped to provide an interface or capability, which can increase the storage of custom information in the add and elementsContainedBy functions of IPv4AddressTrie (this data is the custom information of the caller and is transparent to the interface provider). This can improve the search performance and reduce the complexity of use.

After supporting the storage of custom information, the coding logic that users need to execute is:
1. Pre-built data
a. Establish an IPv4AddressTrie tree in advance, this part will pass custom information to the add function.

2. Receive a message with the specified destination IP
a. Find the subnet (IPv4TrieNode) and custom information to which it belongs through the destination IP.

**Comment by seancfoley** [comment]
As far as I can tell you just want to use [IPv4AddressAssociativeTrie](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4AddressAssociativeTrie.html).

```java
public class Issue {

	static class Info {
		String str;
		
		Info(String str) {
			this.str = str;
		}
		
		@Override
		public String toString() {
			return "stored info: " + str;
		}
	}
	
	static IPv4Address getAddr(String addrStr) {
		return new IPAddressString(addrStr).getAddress().toIPv4();
	}

	static void addToTrie(IPv4AddressAssociativeTrie<Info> trie, String addrStr, String infoStr) {
		trie.put(getAddr(addrStr).toPrefixBlock(), new Info(infoStr));
	}

	public static void main(String[] args) {
		IPv4AddressAssociativeTrie<Info> trie = new IPv4AddressAssociativeTrie<>();
		addToTrie(trie, "1.1.1.1/24", "my stored info for 1.1.1.0/24");
		addToTrie(trie, "2.2.2.2/24", "my stored info for 2.2.2.2/24");
		addToTrie(trie, "3.3.3.3/32", "my stored info for 3.3.3.2/32");
		addToTrie(trie, "10.1.1.1/16", "my stored info for 10.1.0.0/16");
		addToTrie(trie, "20.1.1.1/24", "my stored info for 20.1.1.0/24");
		addToTrie(trie, "30.1.1.1/32", "my stored info for 30.1.1.1/32");
		
		String ip = "20.1.1.2";
		IPv4AssociativeTrieNode<Info> subnet = trie.elementsContaining(getAddr(ip));
		System.out.println("containing subnet for " + ip + " is " + subnet.getKey());
		Info info = subnet.getValue();
		System.out.println("associated info is " + info);
	}
}
```

Output:

    containing subnet for 20.1.1.2 is 20.1.1.0/24
    associated info is stored info: my stored info for 20.1.1.0/24

**Comment by angelyouyou** [comment]
@seancfoley 
Thank you very much for your help, this method solved my problem. At the same time, there is a suggestion that you can add this code snippet as an example in the example, which can help more people.

**Comment by angelyouyou** [comment]
@seancfoley 
Please teach me:
The current demand is to only include a single IP address or subnet in the string, and hope that there is no address in the specified range.
What kind of interface can be used to achieve this?
E.g:
I want to include only 1.1.1.1, 2.2.2.2/24, but do not want to have addresses in the range of 3.3.3.3-4.

**Comment by seancfoley** [comment]
When using address tries, you must use prefix blocks like 2.2.2.0/24 or single addresses like 1.1.1.1.

You can [use HostName](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#check-if-string-is-an-ip-address-or-host-name) to check if something is a host name like "www.google.com" or is an address like the others you listed.

Or you can just parse with IPAddressString, since "www.google.com" is not parse as an address, so IPAddressString.toAddress() will throw an exception and getAddress() will return null.

As for "1.1.1.1-2", "2001::1-2", you can prevent those from being parsed by IPAddressString by using [IPAddressStringParameters](https://seancfoley.github.io/IPAddress/ipaddress.html#address-or-host-name-validation-options).  Another example of using IPAddressStringParameters is [here](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#control-parsing-of-ip-addresses-with-fewer-segments-than-standard).  To prevent ranges like 1-2, you would use [setRangeOptions(RangeParameters.NO_RANGE)](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/AddressStringParameters.RangeParameters.html#NO_RANGE).

Another alternative is to [convert addresses like that to prefix blocks](https://seancfoley.github.io/IPAddress/ipaddress.html#partitioning-subnets), using partitionWithSpanningBlocks or partitionWithSingleBlockSize.

**Comment by angelyouyou** [comment]
@seancfoley Thanks very much.
Now I have an address with BigInteger type(maybe ipv4 or ipv6 address, but I do not know the address is ipv4 or ipv6 type).
How can I get the IPAddress or IPAddressString object with the current API?

**Comment by seancfoley** [comment]
An integer on its own is not enough to know if IPv4 or IPv6.  Consider the integer 0, or 1, or 4294967295.  Those could be 0.0.0.0, 0.0.0.1, and 255.255.255.255, or they could be ::, ::1, ::ffff:ffff.  In general, you need to know how many bits are used by the address (32 for IPv4 or 128 for IPv6), and not the value alone to know what IP version, unless the integer is larger than 4294967295, in which case it can only be IPv6, since it needs to use at least 33 bits to store the number. 

For IPv6 use [this](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#ipv6-to-biginteger-and-back)

For IPv4, change BigInteger to int with BigInteger.intValue() then use [this](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#ipv4-to-int-and-back)

**Comment by angelyouyou** [comment]
public static boolean checkHostIdentifierString(HostIdentifierString ipAddrStr) {
        if (ipAddrStr == null) {
            return false;
        }

        if (ipAddrStr.getAddress() != null) {
            LOGGER.info("{} [***is] identifier address.", ipAddrStr.toString());
            return true;
        } else {
            LOGGER.info("{} is not identifier address.", ipAddrStr.toString());
            return false;
        }
    }
public static boolean isIPv6CIDRAddrBlock(String ipAddrStr) {
        IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
                allowEmpty(false).
                allowPrefixOnly(true).setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE).
                allowMask(false).
                allowIPv4(false).
                allow_inet_aton(false).toParams();

        return checkHostIdentifierString(new IPAddressString(ipAddrStr, strParams));
    }

**Comment by seancfoley** [comment]
That looks fine if your intention is to parse only IPV6.

By creating your own IPAddressString subclass you can avoid having to pass in the string params each time.

	static final IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
			allowEmpty(false).
			allowPrefixOnly(true).
			setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE).
			allowMask(false).
			allowIPv4(false).toParams();
	
	static class MyIPv4AddressString extends IPAddressString {
		MyIPv4AddressString(String str) {
			super(str, strParams);
		}
	}
	
	public static boolean isIPv6CIDRAddrBlock(String ipAddrStr) {
		return checkHostIdentifierString(new MyIPv4AddressString(ipAddrStr));
	}

**Comment by angelyouyou** [comment]
> Another alternative is to [convert addresses like that to prefix blocks](https://seancfoley.github.io/IPAddress/ipaddress.html#partitioning-subnets), using partitionWithSpanningBlocks or partitionWithSingleBlockSize. You can check if something is a single prefix block (does not need to be partitioned) using [isSinglePrefixBlock()](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/Address.html#isSinglePrefixBlock--)
@seancfoley 
How Can I add Partitioned CIDR block to a IPv4AddressTrie tree?
The example below can only add to a trie.
Partition.partitionWithSingleBlockSize(subnet).predicateForEach(trie::add);
