### ISSUE TITLE
How to make addresses can be superimposed on attributes to reconstruct a search tree. 

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#64]
There are now 3 address sets (the types are all IPv4AddressAssociativeTrie or IPv6AddressAssociativeTrie). Some of these sets of addresses overlap, and some do not.
E.g:
Set 1:
1.1.1.0/24 carries attribute 1 (P1), 2.2.2.0/24 carries attribute 2 (P2)
Set 2:
1.1.1.0/24 carries attribute 1 (P1), 2.2.2.0/24 carries attribute 2 (P2)
Set 3:
1.1.1.0/32 carries attribute 3 (P3), 2.2.2.1/32 carries attribute 4 (P2), 3.3.3.3/32 carries attribute 4 (P4)
Now I hope that these addresses can be superimposed on attributes to reconstruct a search tree. The desired result (the type is still IPv4AddressAssociativeTrie or IPv6AddressAssociativeTrie) is as follows to support quick search (the following is expressed in the form of Range or CIDR for easy reading):
Set 1:
1.1.1.0/32 carries attribute 1 (P1) and attribute 3 (P3)
Set 2:
1.1.1.1-254 Carrying attribute P1
Set 3:
2.2.2.1/32 carries attribute 2 (P2) and attribute 4 (P4)
Set 4:
2.2.2.0/32, 2.2.2.2-255 carry attribute 2 (P2)
Set 5:
3.3.3.3/32 Carry Attribute 4 (P4)

What kind of ideas and main API interfaces can be used to achieve this goal? thank you very much.

**Comment by seancfoley** [comment]
You cannot use subnets like 1.1.1.1-254 or 2.2.2.2-255 as keys in a trie since they are not prefix blocks.

You could use them as keys in a different data structure (hash map or tree map), 
but then you would lose the ability to do lookups by containment.

You could partition those keys into cidr blocks in order to map each one to the correct mapping, 
but then the trie gets much larger, and also, 
figuring out those key-mapping pairs to be partitioned becomes quite complicated, 
you would have to compare the new blocks with what is already in the trie, 
and rearrange a large part of the existing trie each time you add a new subnet.

Instead, the simple way to do this is to create a trie using the original mappings, then simply modify the lookup, 
to first find the longest prefix match for the subnet key, 
and then to move up the trie towards the root to find all additional mappings for the same key. 

So for instance, with your mappings:
1.1.1.0/24 carries attribute 1 (P1), 2.2.2.0/24 carries attribute 2 (P2)
1.1.1.0/32 carries attribute 3 (P3), 2.2.2.1/32 carries attribute 4 (P4), 3.3.3.3/32 carries attribute 4 (P4)

	 enum Att {
		  P1,
		  P2,
		  P3,
		  P4,
		}
	
	public static void main(String[] args) {
		IPv4AddressAssociativeTrie<Att> trie = new IPv4AddressAssociativeTrie<>();
		add(trie, "1.1.1.0/24", Att.P1);
		add(trie, "2.2.2.0/24", Att.P2);
		add(trie, "1.1.1.0/32", Att.P3);
		add(trie, "2.2.2.1/32", Att.P4);
		add(trie, "3.3.3.3/32", Att.P4);
		
		System.out.println(trie);
		
		match(trie, "1.1.1.0");
		match(trie, "1.1.1.1");
		match(trie, "2.2.2.1");
		match(trie, "2.2.2.0");
		match(trie, "2.2.2.255");
		match(trie, "3.3.3.3/32");
	}

	static void add(IPv4AddressAssociativeTrie<Att> trie, String addrStr, Att val) {
		trie.put(new IPAddressString(addrStr).getAddress().toIPv4(), val);
	}
	
	static void match(IPv4AddressAssociativeTrie<Att> trie, String addrStr) {
		IPv4Address addr = new IPAddressString(addrStr).getAddress().toIPv4();
		IPv4AssociativeTrieNode<Att> result = trie.longestPrefixMatchNode(addr);
		System.out.println("Longest prefix match for " + addr + " is " + result.getKey() + " with " + result.getValue());
		IPv4AssociativeTrieNode<Att>  parent = result.getParent();
		while(parent != null) {
			if(parent.isAdded()) {
				System.out.println("additional match for " + addr + " is " + parent.getKey() + " with " + parent.getValue());
			}
			parent = parent.getParent();
		}
		System.out.println();
	}

Output:

```
○ 0.0.0.0/0 = null (5)
└─○ 0.0.0.0/6 = null (5)
  ├─● 1.1.1.0/24 = P1 (2)
  │ └─● 1.1.1.0 = P3 (1)
  └─○ 2.0.0.0/7 = null (3)
    ├─● 2.2.2.0/24 = P2 (2)
    │ └─● 2.2.2.1 = P4 (1)
    └─● 3.3.3.3 = P4 (1)

Longest prefix match for 1.1.1.0 is 1.1.1.0 with P3
additional match for 1.1.1.0 is 1.1.1.0/24 with P1

Longest prefix match for 1.1.1.1 is 1.1.1.0/24 with P1

Longest prefix match for 2.2.2.1 is 2.2.2.1 with P4
additional match for 2.2.2.1 is 2.2.2.0/24 with P2

Longest prefix match for 2.2.2.0 is 2.2.2.0/24 with P2

Longest prefix match for 2.2.2.255 is 2.2.2.0/24 with P2

Longest prefix match for 3.3.3.3/32 is 3.3.3.3 with P4
```
As you can see this matches your expectations.

**Comment by seancfoley** [comment]
Now, if you didn't want to do this advanced lookup, you can conduct a second trie, by iterating through this trie, and for each mapping, add to the second trie.  For instance, you would map 1.1.1.0 to a type like a List that has both P1 and P3.  And you would map 1.1.1.0/24 to P1 again.  But, this doesn't really gain you much, so I would just stick with the solution above.
