### ISSUE TITLE
How to Search an AssociativeAddressTrie with range address?

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#65]
I built an AssociativeAddressTrie, and translate range address to CIDR block for adding the addresses.
When I search the range address whether on the trie, I have no idea how to search it.
Such as I add addresses(1.2.1-7.*) to trie, and I want to search the address(1.2.1-7.*).
How to implement for searching it? Thanks very much.
@seancfoley

**Comment by seancfoley** [comment]
Well, I answered your question #64 which you just closed, which may or may not be related this question.

**Comment by seancfoley** [comment]
Tries can only use CIDR prefix blocks or individual addresses as keys.

Most of the time, tries contain CIDR prefix blocks, and tries are searched with individual addresses.

You can use one of the partition options like in #63.  Here I use a simpler partition option, just partition into individual addresses by iterating.

	public static void main(String[] args) throws AddressStringException, IncompatibleAddressException {
		IPv4AddressTrie trie = new IPv4AddressTrie();
		IPv4Address addrs = new IPAddressString("1.2.1-7").toAddress().toIPv4();
		for(IPv4Address addr : addrs.getIterable()) {
			trie.add(addr);
		}
		boolean allInTrie = true;
		for(IPv4Address addr : addrs.getIterable()) {
			boolean cont = trie.contains(addr);
			System.out.println(addr + " in trie " + cont);
			allInTrie &= cont;
		}
		System.out.println("all in trie " + allInTrie);
	}

Output:

    1.2.0.1 in trie true
    1.2.0.2 in trie true
    1.2.0.3 in trie true
    1.2.0.4 in trie true
    1.2.0.5 in trie true
    1.2.0.6 in trie true
    1.2.0.7 in trie true
    all in trie true

**Comment by angelyouyou** [comment]
> "1.2.1-7"

@seancfoley 
Thanks.I noticed the CIDR translator for adding or search.
If the address added is "1.2.1-7.*", and need to search the address "1.2.1-7.*".
Can I also use the code you just wrote above?

**Comment by seancfoley** [comment]
You can use any code I write in here.  

There is no high performance way to search other than search one by one.  The reason is that there are an infinite number of ways that subnets can intersect, if you allow subnets to have no pre-defined structure.  But when you start working with CIDR blocks, there are no longer such a huge range of possibilities.  If you have two CIDR blocks, then they either do not intersect at all, or one is contained in the other.  Those are the only possibilities.  So you can have a containment hierarchy that can be modeled by a tree. 

That is a big reason (maybe the main reason) why IPv4 or IPV6 routing is typically done with CIDR blocks.

The partition classes I wrote provide two ways to convert to CIDR blocks.  Or the code above.

You can also always test for CIDR blocks using isPrefixBlock() or isSinglePrefixBlock().
