### ISSUE TITLE
Issue with getting Start / End IPs of a CIDR

### ISSUE THREAD

**Issue by ahmompoint** [seancfoley/IPAddress#71]
When I use the following code:         
`IPAddressString` ipAddressCidrString = new `IPAddressString("116.68.170.157/24");
String startIp = ipAddressCidrString.getAddress().getLower().withoutPrefixLength().toString();
String endIp = ipAddressCidrString.getAddress().getUpper().withoutPrefixLength().toString();`

I get back `startIp = 116.68.170.157, endIp = 116.68.170.157.` I'd expect to get back `116.68.170.0` - `116.68.170.255`

When I use `ipAddressCidrString.getAddress().toPrefixblock()` it returns the correct thing? Can you explain why the first one is wrong? 

Note: `IPAddressString ipAddressCidrString = new IPAddressString("1.0.0.0/24");` works as expected which is why I am confused, thanks!

**Comment by seancfoley** [comment]
The address 116.68.170.157/24 is the same address as 116.68.170.157, it's just a single address.
That's because the host, .157, is not zero.  So it's just a single address with an associated prefix length.
So getting either the lower or upper in the range will both get the same address 116.68.170.157 as well.
	
1.0.0.0/24 works differently because the host, ".0", is zero.  So it is considered to be the subnet for that prefix, and therefore has the full range of hosts for that subnet.  It is equivalent to 1.0.0.0-255.

As you have discovered, if you always want the subnet, then use toPrefixBlock() after parsing.
	
This is quite similar to issues #26, issue #30, issue #40, issue #45, issue #51, issue #54, issue #57 and also similar to issue #39 and issue #53.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address).

**Comment by ahmompoint** [comment]
Thank you for the quick response!
