### ISSUE TITLE
Introduce IPv6AddressStringParameters.Builder::allowIPv4Mapped(boolean allow)

### ISSUE THREAD

**Issue by igor-tsiglyar** [seancfoley/IPAddress#75]
Hi @seancfoley!

Thanks a lot for the hard work on this library. I am suggesting the new option `IPv6AddressStringParameters.Builder::allowIPv4Mapped(boolean allow)` to be added that would allow us to declaratively forbid IPv4-mapped IPv6 addresses in a form of `::ffff:c0a8:0a14` which is the same as `::ffff:192.168.10.20` that can already be handled with `allowMixed(false)`.

Best Regards,
Igor

**Comment by seancfoley** [comment]
I've given this some thought.  The underlying issue is that in order to know whether an address is IPv4-mapped, you first have to parse it, and then compare the initial six segment values with ::ffff.  Because of tht, it doesn't make sense to make "IPv4-mapped" a validation option; the validation is already over by the time you can check.

That being said, it is possible to do the check prior to converting to an IPAddress object (as in the code shown above).  This can be done using the IPAddressString.prefixEquals method.  So I am adding the method isIPv4Mapped to IPAddressString which will do just that, allowing the check for IPv4-mapped to be done entirely with an IPAddressString instance.

This is being added to the next release.

**Comment by seancfoley** [comment]
The method IPAddressString.isIPv4Mapped has been added to the latest version 5.3.4
