### ISSUE TITLE
IPv6 upper & lower not being returned accurately.

### ISSUE THREAD

**Issue by stykiaz** [seancfoley/IPAddress#8]
We noticed that in some cases the getUpper() & getLower() for ipv6 is producing unexpected results.

Examples:
Case 1: this works as expected.
```
IPv6Address rangeString1 = new IPAddressString("2001:470:7:a00::/56").getAddress().toIPv6()
rangeString1.getUpper().toAddressString() //produces 2001:470:7:aff:ffff:ffff:ffff:ffff/56
rangeString1.getLower().getSection().toString() //produces 2001:470:7:a00:0:0:0:0/56
```

Case 2: this doesn't work as expected. Doesn't produce upper & lower bounds
```
IPv6Address rangeString = new IPAddressString("2001:470:7:a00::/53").getAddress().toIPv6();
rangeString.getLower().getSection().toString() // produces 2001:470:7:a00:0:0:0:0/53 (as expected)
rangeString.getUpper().getSection().toString() // produces 2001:470:7:a00:0:0:0:0/53 which I believe to be wrong 
```

Thanks

**Comment by seancfoley** [comment]
Hello, this is working as intended.

The default behaviour is that an address whose host bits are all zeros is considered to be the full network for that prefix length.

In this case, with a prefix of 53, each segment length is 16 bits, so a prefix of 53 ends up including the first 3 segments of 16 bits and the first 5 bits in the 4th segment.  The 4th segment has value 0a00.  

The bits for 0a00 are:

0000 1010 0000 0000

Dividing the network and host at the 5th bit gives:

0000 1 <---network---host ---> 010 0000 0000

So the host is not all zeros, the second bit in the host is '1', so the address is considered to be the single address 2001:470:7:a00:: along with a prefix length of 53.  Since it is just a single address the upper and lower are the same and also have value 2001:470:7:a00::/53

In the case of prefix length 56, dividing network and host is:

0000 1010 <---network---host ---> 0000 0000

In that cases the host is all zeros and so it is considered to be the full network which ranges from 2001:470:7:a00:0:0:0:0/56 to 2001:470:7:aff:ffff:ffff:ffff:ffff/56

This behaviour (ie the all-zeros host is considered to be the full network) is documented at https://seancfoley.github.io/IPAddress/#_Prefix_Length_Handling with the option PREFIXED_ZERO_HOSTS_ARE_SUBNETS

It is possible to change this behaviour and parse all addresses as prefix length as networks, using the option ALL_PREFIXED_ADDRESSES_ARE_SUBNETS with the method https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4AddressNetwork.html#setDefaultPrefixConfiguration-inet.ipaddr.AddressNetwork.PrefixConfiguration-

It is also possible to simply get the full network at any time using the method toPrefixBlock https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv6/IPv6Address.html#toPrefixBlock--

Using that method you would have:

    IPAddressString rangeStringStr = new IPAddressString("2001:470:7:a00::/53");
    IPv6Address rangeString = rangeStringStr.getAddress().toPrefixBlock().toIPv6();
    System.out.println(rangeString.getLower().toString()); // produces 2001:470:7:800:0:0:0:0/53
    System.out.println(rangeString.getUpper().toString()); // produces 2001:470:7:fff:ffff:ffff:ffff:ffff/53


Quite possible you actually wanted the 4th segment to be a000, not a00, which would give:

    IPAddressString rangeStringStr = new IPAddressString("2001:470:7:a000::/53");
    IPv6Address rangeString = rangeStringStr.getAddress().toIPv6();
    System.out.println(rangeString.getLower().toString()); // produces 2001:470:7:a000:0:0:0:0/53
    System.out.println(rangeString.getUpper().toString()); // produces produces 2001:470:7:a7ff:ffff:ffff:ffff:ffff/53

Hope that explains things.

**Comment by stykiaz** [comment]
Thanks a lot for clarifying, much appreciated. We started using toMaxHost() method instead which seems to be giving us the desired results.
