### ISSUE TITLE
Is there a high performance way to check IP addresses collection (containment relationship) exist in a containment relationship ?

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#84]
@seancfoley
Sorry for not replying to your message in time.
Returning true in my example means there is an address conflict (containment relationship) in the collection, otherwise it doesn't.
Case 1:
{1.1.1.1/24, 1.1.1.3/32, 2.2.2.2/24}
Since 1.1.1.1/24 contains the address 1.1.1.3/32, there is an address conflict (containment relationship), so it returns true.

Case 2:
{1.1.1.1/24, 3.1.1.3/32, 2.2.2.2/24}
These 3 addresses do not have any conflict (inclusive relationship), so return false.

Is there a high performance way to check the confliction in a address collection?

**Comment by seancfoley** [comment]
There are two ways that come to mind.

The simplest is to sort such a list by lowest address in each subnet.  Then go through the sorted list one-by-one, checking if the lowest address of the element that follows in the list is exceeded by the highest address of the current element in the list.  If so, the current contains the following in the list, and so the check returns true.  If you get through the whole list without that happening, then the check returns false.

If the collection were to remain fairly constant and you wanted to repeat this check with a number of new addresses, then you could construct an address trie with all you addresses to check.  Then with any new or existing address in the trie, call the trie methods elementsContainedBy and elementsContaining, then you go though the latter linked list and use an iterator on the former sub-trie to get all the contained and containing address blocks.  If there were no containment relationship then both would be empty (except for perhaps the element you are checking), and your check would return false.  Otherwise it would return true.

**Comment by seancfoley** [comment]
You can use [this example](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment,-Matching,-Comparing#select-cidr-prefix-block-subnets-intersecting-with-arbitrary-block).  Construct a trie as shown with all your blocks (don't forget to convert to blocks using toPrefixBlock), then use elementsContaining and elementsContainedBy with each one.
