### ISSUE TITLE
How to quickly find all group objects that may be associated with a specific IP address

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#95]
We have a requirement regarding the matching of IP addresses with their associated group objects. We hope to quickly find  all group objects that may be associated with a specific IP address (often the destination IP, such as 1.1.1.1).
Ask if and how to implement it through the IPAddressTrie tree, thank you very much.

E.g:
Group1 associated address {1.1.1.0/24, 2.2.2.2}
group2 associated address (1.1.1.1/32, 3.3.3.3/32)
Group3 associated address (2.2.*.*, 4.4.4.4)

When searching for the group objects associated with the IP address 1.1.1.1, it is hoped that group1 and group2 can be quickly found.
When searching for the group object associated with the IP address 2.2.2.2, it is hoped that group2 and group3 can be quickly found.
When searching for the group object associated with the IP address 3.3.3.3, it is hoped that group2 can be quickly found.
When searching for the group object associated with the IP address 4.4.4.4, it is hoped that group2 and group3 can be quickly found.

The format of one or more IP addresses associated with a group object may be a single IP address (such as 1.1.1.1), CIDR format (1.1.1.0/24) or range format (1.2.*.*, 1.2.0- 255.0-255).

**Comment by seancfoley** [comment]
Allowing the range format can be problematic, since you can come up with some pathological cases like 
255.255.255.1-255, which is 16 million disjoint address ranges.  However, the example you gave, 1.2.0- 255.0-255, is just a single disjoint range, and it is also equivalent to a single prefix block 1.2.0.0/16.

In general, for the range formats, since they are not always prefix blocks, you would need to use the SequentialBlockIterator to split up the disjoint ranges, and then use SpanWithPrefixBlocks to get the equivalent prefix blocks.  The Partition class may already have code to do this.  This would work fine with any address, but for prefix blocks and single addresses the result would just be the same block or address.  For the range formats you would end up with many.

Seems fine overall.  There is a [wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment,-Matching,-Comparing#look-up-associated-ip-address-data-by-containing-subnet-or-matching-address) for doing lookups with tries.

There is no specific question or issue to address here, so closing.
