### ISSUE TITLE
Upper bound doesn't work properly

### ISSUE THREAD

**Issue by PrajwalKrishna** [seancfoley/IPAddress#96]
On running -
`new IPAddressString("235.234.5.6/4").getAddress().toPrefixBlock().toIPv4().upperLongValue()`

The output is - 3774873599
Whereas, the expected output was - 4026531839

On using the `toUpper()` I am getting the expected output - 239.255.255.255.
On converting this to `toUpper().longValue()`, I am getting the expected output -  4026531839

**Comment by seancfoley** [comment]
You are correct, the bug is [here](https://github.com/seancfoley/IPAddress/blob/master/IPAddress/src/inet.ipaddr/inet/ipaddr/ipv4/IPv4AddressSection.java#L544) where the code grabs the lower and not the upper value for the first segment.

The fix will be delivered in a release quite soon, likely in a few weeks.

In the meantime, you've already identified the work-around.

**Comment by PrajwalKrishna** [comment]
Thanks for prompt response.

**Comment by seancfoley** [comment]
This was fixed in [version 5.4.0](https://github.com/seancfoley/IPAddress/releases/tag/v5.4.0).  Closing.
