### ISSUE TITLE
puzzling behaviour with leading zeros

### ISSUE THREAD

**Issue by lneves** [seancfoley/IPAddress#99]
Hi!

This code:
```
IPAddressString ipstr0 = new IPAddressString("89.000.94.209");
IPAddress ip0 = ipstr0.getAddress();
System.out.println(ip0);

IPAddressString ipstr1 = new IPAddressString("89.000.094.209");
IPAddress ip1 = ipstr1.getAddress();
System.out.println(ip1);
```

Generates this output:
```
89.0.94.209
null
```

Why does parsing "89.000.094.209" results in "null"? Is this a bug? A misunderstanding on my part on what  is the behaviour of the default validation options?
(using version "5.4.0")

**Comment by seancfoley** [comment]
Hello.  Firstly, you can use [toAddress to get an exception](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressString.html#toAddress--).  It is the same as getAddress but throws exceptions for invalid addresses instead of returning null.

Secondly, this behaviour is [explained somewhat here](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#control-parsing-of-ip-addresses-with-fewer-segments-than-standard),  and [somewhat here](https://seancfoley.github.io/IPAddress/ipaddress.html#parse-string-representation-of-ip-address-or-host-name).

In summary, when you put a 0 in front of an IPv4 address value, [it is, by default, considered to be octal](https://linux.die.net/man/3/inet_aton).  This is known as BSD-style format for IPv4.  It originated with a routine known as inet_aton.   If you put a similar address in your browser, [http://89.000.074.209](http://89.000.074.209), you can see it is changed to http://89.0.60.209/.  That is because 074 in octal is 60 decimal.

However, in your case, you used 094 octal, which is an invalid value, since octal does not allow '9' digits.  So it is an invalid address.  If you put [http://89.000.074.209](http://89.000.074.209) in your browser you can see it is no longer considered an IPv4 address, and will likely do a search with it as a string.

You can use search parameters with this library to treat it as a decimal value.  Example [here of using IPAddressStringParameters](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#control-parsing-of-ip-addresses-with-fewer-segments-than-standard).  Use the setting [allow_inet_aton_octal](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4AddressStringParameters.Builder.html#allow_inet_aton_octal-boolean-).

**Comment by seancfoley** [comment]
If you have further wues

**Comment by seancfoley** [comment]
If you have further questions, feel free to ask.

**Comment by lneves** [comment]
Thanks for the explanation!
